---
- name: Create Additional DNS Records
  hosts: all
  vars:
  gather_facts: no
  tasks:

  #connect directly to the domain controller add dns records

  - win_domain_membership:
      dns_domain_name: {{domain}}
      domain_admin_user: {{domain_user}}
      domain_admin_password: {{domain_password}}
      state: domain
    register: domain_state

  - win_reboot:
    when: domain_state.reboot_required
